CREATE TABLE hotel_bookings (
    customer_id INTEGER NOT NULL,
    property_id INTEGER NOT NULL,
    city VARCHAR(50),
    star_rating INTEGER,
    booking_date DATE,
    check_in_date DATE,
    check_out_date DATE,
    room_type VARCHAR(20),
    num_rooms_booked INTEGER,
    stay_type VARCHAR(20),
    booking_channel VARCHAR(50),
    booking_value NUMERIC(12,2),
    costprice NUMERIC(12,2),
    markup NUMERIC(12,2),
    selling_price NUMERIC(12,2),
    payment_method VARCHAR(20),
    refund_status VARCHAR(10),
    refund_amount NUMERIC(12,2),
    channel_of_booking VARCHAR(50),
    booking_status VARCHAR(20),
    travel_date DATE,
    cashback NUMERIC(12,2),
    coupon_redeem NUMERIC(12,2),
    "Coupon Used?" VARCHAR(10),
    PRIMARY KEY (customer_id)
);